[package]
name = "squid"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 0
debug = true

[dependencies]
hyper = { version = "0.14", features = [ "full" ] }
hyper-tls = "0.5.0"

tonic = { version = "0.8.3", features = [ "tls", "gzip" ] }
tokio = { version = "1.23.0", features = [ "rt-multi-thread", "time", "fs", "macros", "net" ] }
futures = { version = "0.3.25", default-features = false, features = [ "alloc" ] }
rayon = "1.6.1"

dotenv = "0.15.0"
serde = "1.0.151"

[build-dependencies]
tonic-build = { version = "0.8.2", features = [ "prost" ] }