update_frequency_sec: 900 # in seconds

services:
  - name: gravitalia # collection name
    algorithm: Hashmap # Only Hashmap is disponible.
    max_words: 5 # maximum words output, max. value: 255
    message_type: Anything # Anything, Word or Hashtag
    exclude: [] # words or hashtags to exclude in search
