[package]
name = "squid-db"

version.workspace = true
description.workspace = true
readme.workspace = true
edition.workspace = true

[dependencies]
bincode = "1"
lz4 = { version = "1.24", optional = true }
serde = { version = "1", features = ["derive"] }

[features]
compress = ["lz4"]
