[package]
name = "squid"

version.workspace = true
description.workspace = true
readme.workspace = true
edition.workspace = true

[[example]]
name = "client"

[dependencies]
zmq = "0"
rmp = "0.8"

fern = "0.6"
log = "0.4"

squid-db = { path = "../squid-db" }
