name: Squid/rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build, clippy, test & bench
    strategy:
      matrix:
        toolchain: [stable]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 1440
    steps:
    - uses: actions/checkout@v3
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
      if: runner.os == 'Windows'
    - run: vcpkg install openssl:x64-windows-static-md
      if: runner.os == 'Windows'
    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
    - name: Build
      run: cargo build
    #- name: Clippy
    #  run: cargo clippy
    - name: Test
      run: cargo test
    - name: Benchmarks
      run: cargo bench
